#!/bin/bash

# Specify the number of terminals you want to open
num_terminals=3
conda_env="hummingbot"
script_path="./run"
project_dir="/Users/devloper/Documents/working/humming_bot/waj_humming_bot/hummingbot"
INFILE=args.txt
IFS=$'\n'
read -d '' -r -a lines < $INFILE
echo "${lines[0]}"
# Loop to open n terminals
for ((i=0; i<$num_terminals; i++)); do
  # Open a new Terminal and run the script
  password=${lines[i]}
  script="$script_path $password"
  echo "$script"
  osascript -e "tell app \"Terminal\"
    do script \"cd $project_dir && $script\"
  end tell"
done
