#!/bin/bash
echo "Here is password$1"

echo "API_KEY =$3"

echo "Secret KEy =$2"


cd /Users/devloper/Documents/working/humming_bot/waj_humming_bot/hummingbot
eval "$(conda shell.bash hook)"
conda activate hummingbot

python ./bin/hummingbot_quickstart.py -p $1 -f conf_perpetual_market_making_binance_testnet.yml -s $2 -a $3
